// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cardchain/cardchain/card.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../cosmos/base/v1beta1/coin";

export const protobufPackage = "cardchain.cardchain";

export enum CardStatus {
  none = 0,
  scheme = 1,
  prototype = 2,
  trial = 3,
  permanent = 4,
  suspended = 5,
  banned = 6,
  bannedSoon = 7,
  bannedVerySoon = 8,
  adventureItem = 9,
  UNRECOGNIZED = -1,
}

export function cardStatusFromJSON(object: any): CardStatus {
  switch (object) {
    case 0:
    case "none":
      return CardStatus.none;
    case 1:
    case "scheme":
      return CardStatus.scheme;
    case 2:
    case "prototype":
      return CardStatus.prototype;
    case 3:
    case "trial":
      return CardStatus.trial;
    case 4:
    case "permanent":
      return CardStatus.permanent;
    case 5:
    case "suspended":
      return CardStatus.suspended;
    case 6:
    case "banned":
      return CardStatus.banned;
    case 7:
    case "bannedSoon":
      return CardStatus.bannedSoon;
    case 8:
    case "bannedVerySoon":
      return CardStatus.bannedVerySoon;
    case 9:
    case "adventureItem":
      return CardStatus.adventureItem;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CardStatus.UNRECOGNIZED;
  }
}

export function cardStatusToJSON(object: CardStatus): string {
  switch (object) {
    case CardStatus.none:
      return "none";
    case CardStatus.scheme:
      return "scheme";
    case CardStatus.prototype:
      return "prototype";
    case CardStatus.trial:
      return "trial";
    case CardStatus.permanent:
      return "permanent";
    case CardStatus.suspended:
      return "suspended";
    case CardStatus.banned:
      return "banned";
    case CardStatus.bannedSoon:
      return "bannedSoon";
    case CardStatus.bannedVerySoon:
      return "bannedVerySoon";
    case CardStatus.adventureItem:
      return "adventureItem";
    case CardStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum CardRarity {
  common = 0,
  uncommon = 1,
  rare = 2,
  exceptional = 3,
  unique = 4,
  UNRECOGNIZED = -1,
}

export function cardRarityFromJSON(object: any): CardRarity {
  switch (object) {
    case 0:
    case "common":
      return CardRarity.common;
    case 1:
    case "uncommon":
      return CardRarity.uncommon;
    case 2:
    case "rare":
      return CardRarity.rare;
    case 3:
    case "exceptional":
      return CardRarity.exceptional;
    case 4:
    case "unique":
      return CardRarity.unique;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CardRarity.UNRECOGNIZED;
  }
}

export function cardRarityToJSON(object: CardRarity): string {
  switch (object) {
    case CardRarity.common:
      return "common";
    case CardRarity.uncommon:
      return "uncommon";
    case CardRarity.rare:
      return "rare";
    case CardRarity.exceptional:
      return "exceptional";
    case CardRarity.unique:
      return "unique";
    case CardRarity.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum CardClass {
  nature = 0,
  culture = 1,
  mysticism = 2,
  technology = 3,
  UNRECOGNIZED = -1,
}

export function cardClassFromJSON(object: any): CardClass {
  switch (object) {
    case 0:
    case "nature":
      return CardClass.nature;
    case 1:
    case "culture":
      return CardClass.culture;
    case 2:
    case "mysticism":
      return CardClass.mysticism;
    case 3:
    case "technology":
      return CardClass.technology;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CardClass.UNRECOGNIZED;
  }
}

export function cardClassToJSON(object: CardClass): string {
  switch (object) {
    case CardClass.nature:
      return "nature";
    case CardClass.culture:
      return "culture";
    case CardClass.mysticism:
      return "mysticism";
    case CardClass.technology:
      return "technology";
    case CardClass.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum CardType {
  place = 0,
  action = 1,
  entity = 2,
  headquarter = 3,
  UNRECOGNIZED = -1,
}

export function cardTypeFromJSON(object: any): CardType {
  switch (object) {
    case 0:
    case "place":
      return CardType.place;
    case 1:
    case "action":
      return CardType.action;
    case 2:
    case "entity":
      return CardType.entity;
    case 3:
    case "headquarter":
      return CardType.headquarter;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CardType.UNRECOGNIZED;
  }
}

export function cardTypeToJSON(object: CardType): string {
  switch (object) {
    case CardType.place:
      return "place";
    case CardType.action:
      return "action";
    case CardType.entity:
      return "entity";
    case CardType.headquarter:
      return "headquarter";
    case CardType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Card {
  owner: string;
  artist: string;
  content: Uint8Array;
  imageId: number;
  fullArt: boolean;
  notes: string;
  status: CardStatus;
  votePool: Coin | undefined;
  voters: string[];
  fairEnoughVotes: number;
  overpoweredVotes: number;
  underpoweredVotes: number;
  inappropriateVotes: number;
  nerflevel: number;
  balanceAnchor: boolean;
  starterCard: boolean;
  rarity: CardRarity;
}

export interface TimeStamp {
  timeStamp: number;
}

function createBaseCard(): Card {
  return {
    owner: "",
    artist: "",
    content: new Uint8Array(0),
    imageId: 0,
    fullArt: false,
    notes: "",
    status: 0,
    votePool: undefined,
    voters: [],
    fairEnoughVotes: 0,
    overpoweredVotes: 0,
    underpoweredVotes: 0,
    inappropriateVotes: 0,
    nerflevel: 0,
    balanceAnchor: false,
    starterCard: false,
    rarity: 0,
  };
}

export const Card: MessageFns<Card> = {
  encode(message: Card, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    if (message.artist !== "") {
      writer.uint32(18).string(message.artist);
    }
    if (message.content.length !== 0) {
      writer.uint32(26).bytes(message.content);
    }
    if (message.imageId !== 0) {
      writer.uint32(32).uint64(message.imageId);
    }
    if (message.fullArt !== false) {
      writer.uint32(40).bool(message.fullArt);
    }
    if (message.notes !== "") {
      writer.uint32(50).string(message.notes);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.votePool !== undefined) {
      Coin.encode(message.votePool, writer.uint32(66).fork()).join();
    }
    for (const v of message.voters) {
      writer.uint32(114).string(v!);
    }
    if (message.fairEnoughVotes !== 0) {
      writer.uint32(72).uint64(message.fairEnoughVotes);
    }
    if (message.overpoweredVotes !== 0) {
      writer.uint32(80).uint64(message.overpoweredVotes);
    }
    if (message.underpoweredVotes !== 0) {
      writer.uint32(88).uint64(message.underpoweredVotes);
    }
    if (message.inappropriateVotes !== 0) {
      writer.uint32(96).uint64(message.inappropriateVotes);
    }
    if (message.nerflevel !== 0) {
      writer.uint32(104).int64(message.nerflevel);
    }
    if (message.balanceAnchor !== false) {
      writer.uint32(120).bool(message.balanceAnchor);
    }
    if (message.starterCard !== false) {
      writer.uint32(128).bool(message.starterCard);
    }
    if (message.rarity !== 0) {
      writer.uint32(136).int32(message.rarity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Card {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.artist = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.imageId = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.fullArt = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.votePool = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.voters.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.fairEnoughVotes = longToNumber(reader.uint64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.overpoweredVotes = longToNumber(reader.uint64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.underpoweredVotes = longToNumber(reader.uint64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.inappropriateVotes = longToNumber(reader.uint64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.nerflevel = longToNumber(reader.int64());
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.balanceAnchor = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.starterCard = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.rarity = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Card {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      artist: isSet(object.artist) ? globalThis.String(object.artist) : "",
      content: isSet(object.content) ? bytesFromBase64(object.content) : new Uint8Array(0),
      imageId: isSet(object.imageId) ? globalThis.Number(object.imageId) : 0,
      fullArt: isSet(object.fullArt) ? globalThis.Boolean(object.fullArt) : false,
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
      status: isSet(object.status) ? cardStatusFromJSON(object.status) : 0,
      votePool: isSet(object.votePool) ? Coin.fromJSON(object.votePool) : undefined,
      voters: globalThis.Array.isArray(object?.voters) ? object.voters.map((e: any) => globalThis.String(e)) : [],
      fairEnoughVotes: isSet(object.fairEnoughVotes) ? globalThis.Number(object.fairEnoughVotes) : 0,
      overpoweredVotes: isSet(object.overpoweredVotes) ? globalThis.Number(object.overpoweredVotes) : 0,
      underpoweredVotes: isSet(object.underpoweredVotes) ? globalThis.Number(object.underpoweredVotes) : 0,
      inappropriateVotes: isSet(object.inappropriateVotes) ? globalThis.Number(object.inappropriateVotes) : 0,
      nerflevel: isSet(object.nerflevel) ? globalThis.Number(object.nerflevel) : 0,
      balanceAnchor: isSet(object.balanceAnchor) ? globalThis.Boolean(object.balanceAnchor) : false,
      starterCard: isSet(object.starterCard) ? globalThis.Boolean(object.starterCard) : false,
      rarity: isSet(object.rarity) ? cardRarityFromJSON(object.rarity) : 0,
    };
  },

  toJSON(message: Card): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.artist !== "") {
      obj.artist = message.artist;
    }
    if (message.content.length !== 0) {
      obj.content = base64FromBytes(message.content);
    }
    if (message.imageId !== 0) {
      obj.imageId = Math.round(message.imageId);
    }
    if (message.fullArt !== false) {
      obj.fullArt = message.fullArt;
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    if (message.status !== 0) {
      obj.status = cardStatusToJSON(message.status);
    }
    if (message.votePool !== undefined) {
      obj.votePool = Coin.toJSON(message.votePool);
    }
    if (message.voters?.length) {
      obj.voters = message.voters;
    }
    if (message.fairEnoughVotes !== 0) {
      obj.fairEnoughVotes = Math.round(message.fairEnoughVotes);
    }
    if (message.overpoweredVotes !== 0) {
      obj.overpoweredVotes = Math.round(message.overpoweredVotes);
    }
    if (message.underpoweredVotes !== 0) {
      obj.underpoweredVotes = Math.round(message.underpoweredVotes);
    }
    if (message.inappropriateVotes !== 0) {
      obj.inappropriateVotes = Math.round(message.inappropriateVotes);
    }
    if (message.nerflevel !== 0) {
      obj.nerflevel = Math.round(message.nerflevel);
    }
    if (message.balanceAnchor !== false) {
      obj.balanceAnchor = message.balanceAnchor;
    }
    if (message.starterCard !== false) {
      obj.starterCard = message.starterCard;
    }
    if (message.rarity !== 0) {
      obj.rarity = cardRarityToJSON(message.rarity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Card>, I>>(base?: I): Card {
    return Card.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Card>, I>>(object: I): Card {
    const message = createBaseCard();
    message.owner = object.owner ?? "";
    message.artist = object.artist ?? "";
    message.content = object.content ?? new Uint8Array(0);
    message.imageId = object.imageId ?? 0;
    message.fullArt = object.fullArt ?? false;
    message.notes = object.notes ?? "";
    message.status = object.status ?? 0;
    message.votePool = (object.votePool !== undefined && object.votePool !== null)
      ? Coin.fromPartial(object.votePool)
      : undefined;
    message.voters = object.voters?.map((e) => e) || [];
    message.fairEnoughVotes = object.fairEnoughVotes ?? 0;
    message.overpoweredVotes = object.overpoweredVotes ?? 0;
    message.underpoweredVotes = object.underpoweredVotes ?? 0;
    message.inappropriateVotes = object.inappropriateVotes ?? 0;
    message.nerflevel = object.nerflevel ?? 0;
    message.balanceAnchor = object.balanceAnchor ?? false;
    message.starterCard = object.starterCard ?? false;
    message.rarity = object.rarity ?? 0;
    return message;
  },
};

function createBaseTimeStamp(): TimeStamp {
  return { timeStamp: 0 };
}

export const TimeStamp: MessageFns<TimeStamp> = {
  encode(message: TimeStamp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timeStamp !== 0) {
      writer.uint32(8).uint64(message.timeStamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TimeStamp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTimeStamp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timeStamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TimeStamp {
    return { timeStamp: isSet(object.timeStamp) ? globalThis.Number(object.timeStamp) : 0 };
  },

  toJSON(message: TimeStamp): unknown {
    const obj: any = {};
    if (message.timeStamp !== 0) {
      obj.timeStamp = Math.round(message.timeStamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TimeStamp>, I>>(base?: I): TimeStamp {
    return TimeStamp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TimeStamp>, I>>(object: I): TimeStamp {
    const message = createBaseTimeStamp();
    message.timeStamp = object.timeStamp ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
