// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cardchain/cardchain/encounter_with_image.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Encounter } from "./encounter";

export const protobufPackage = "cardchain.cardchain";

export interface EncounterWithImage {
  encounter: Encounter | undefined;
  image: string;
}

function createBaseEncounterWithImage(): EncounterWithImage {
  return { encounter: undefined, image: "" };
}

export const EncounterWithImage: MessageFns<EncounterWithImage> = {
  encode(message: EncounterWithImage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encounter !== undefined) {
      Encounter.encode(message.encounter, writer.uint32(10).fork()).join();
    }
    if (message.image !== "") {
      writer.uint32(18).string(message.image);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EncounterWithImage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEncounterWithImage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.encounter = Encounter.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.image = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EncounterWithImage {
    return {
      encounter: isSet(object.encounter) ? Encounter.fromJSON(object.encounter) : undefined,
      image: isSet(object.image) ? globalThis.String(object.image) : "",
    };
  },

  toJSON(message: EncounterWithImage): unknown {
    const obj: any = {};
    if (message.encounter !== undefined) {
      obj.encounter = Encounter.toJSON(message.encounter);
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EncounterWithImage>, I>>(base?: I): EncounterWithImage {
    return EncounterWithImage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EncounterWithImage>, I>>(object: I): EncounterWithImage {
    const message = createBaseEncounterWithImage();
    message.encounter = (object.encounter !== undefined && object.encounter !== null)
      ? Encounter.fromPartial(object.encounter)
      : undefined;
    message.image = object.image ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
