// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cardchain/cardchain/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../cosmos/base/v1beta1/coin";
import { Card, TimeStamp } from "./card";
import { Council } from "./council";
import { Encounter } from "./encounter";
import { Image } from "./image";
import { Match } from "./match";
import { Params } from "./params";
import { RunningAverage } from "./running_average";
import { SellOffer } from "./sell_offer";
import { Server } from "./server";
import { Set } from "./set";
import { User } from "./user";
import { Zealy } from "./zealy";

export const protobufPackage = "cardchain.cardchain";

/** GenesisState defines the cardchain module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  cardRecords: Card[];
  users: User[];
  addresses: string[];
  matches: Match[];
  sets: Set[];
  sellOffers: SellOffer[];
  pools: Coin[];
  cardAuctionPrice: Coin | undefined;
  councils: Council[];
  runningAverages: RunningAverage[];
  images: Image[];
  servers: Server[];
  lastCardModified: TimeStamp | undefined;
  zealys: Zealy[];
  /** this line is used by starport scaffolding # genesis/proto/state */
  encounters: Encounter[];
}

function createBaseGenesisState(): GenesisState {
  return {
    params: undefined,
    cardRecords: [],
    users: [],
    addresses: [],
    matches: [],
    sets: [],
    sellOffers: [],
    pools: [],
    cardAuctionPrice: undefined,
    councils: [],
    runningAverages: [],
    images: [],
    servers: [],
    lastCardModified: undefined,
    zealys: [],
    encounters: [],
  };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.cardRecords) {
      Card.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.users) {
      User.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.addresses) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.matches) {
      Match.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.sets) {
      Set.encode(v!, writer.uint32(58).fork()).join();
    }
    for (const v of message.sellOffers) {
      SellOffer.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.pools) {
      Coin.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.cardAuctionPrice !== undefined) {
      Coin.encode(message.cardAuctionPrice, writer.uint32(90).fork()).join();
    }
    for (const v of message.councils) {
      Council.encode(v!, writer.uint32(98).fork()).join();
    }
    for (const v of message.runningAverages) {
      RunningAverage.encode(v!, writer.uint32(106).fork()).join();
    }
    for (const v of message.images) {
      Image.encode(v!, writer.uint32(114).fork()).join();
    }
    for (const v of message.servers) {
      Server.encode(v!, writer.uint32(122).fork()).join();
    }
    if (message.lastCardModified !== undefined) {
      TimeStamp.encode(message.lastCardModified, writer.uint32(130).fork()).join();
    }
    for (const v of message.zealys) {
      Zealy.encode(v!, writer.uint32(138).fork()).join();
    }
    for (const v of message.encounters) {
      Encounter.encode(v!, writer.uint32(146).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cardRecords.push(Card.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.users.push(User.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.addresses.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.matches.push(Match.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sets.push(Set.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.sellOffers.push(SellOffer.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.pools.push(Coin.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.cardAuctionPrice = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.councils.push(Council.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.runningAverages.push(RunningAverage.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.images.push(Image.decode(reader, reader.uint32()));
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.servers.push(Server.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.lastCardModified = TimeStamp.decode(reader, reader.uint32());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.zealys.push(Zealy.decode(reader, reader.uint32()));
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.encounters.push(Encounter.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      cardRecords: globalThis.Array.isArray(object?.cardRecords)
        ? object.cardRecords.map((e: any) => Card.fromJSON(e))
        : [],
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => User.fromJSON(e)) : [],
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => globalThis.String(e))
        : [],
      matches: globalThis.Array.isArray(object?.matches) ? object.matches.map((e: any) => Match.fromJSON(e)) : [],
      sets: globalThis.Array.isArray(object?.sets) ? object.sets.map((e: any) => Set.fromJSON(e)) : [],
      sellOffers: globalThis.Array.isArray(object?.sellOffers)
        ? object.sellOffers.map((e: any) => SellOffer.fromJSON(e))
        : [],
      pools: globalThis.Array.isArray(object?.pools) ? object.pools.map((e: any) => Coin.fromJSON(e)) : [],
      cardAuctionPrice: isSet(object.cardAuctionPrice) ? Coin.fromJSON(object.cardAuctionPrice) : undefined,
      councils: globalThis.Array.isArray(object?.councils) ? object.councils.map((e: any) => Council.fromJSON(e)) : [],
      runningAverages: globalThis.Array.isArray(object?.runningAverages)
        ? object.runningAverages.map((e: any) => RunningAverage.fromJSON(e))
        : [],
      images: globalThis.Array.isArray(object?.images) ? object.images.map((e: any) => Image.fromJSON(e)) : [],
      servers: globalThis.Array.isArray(object?.servers) ? object.servers.map((e: any) => Server.fromJSON(e)) : [],
      lastCardModified: isSet(object.lastCardModified) ? TimeStamp.fromJSON(object.lastCardModified) : undefined,
      zealys: globalThis.Array.isArray(object?.zealys) ? object.zealys.map((e: any) => Zealy.fromJSON(e)) : [],
      encounters: globalThis.Array.isArray(object?.encounters)
        ? object.encounters.map((e: any) => Encounter.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.cardRecords?.length) {
      obj.cardRecords = message.cardRecords.map((e) => Card.toJSON(e));
    }
    if (message.users?.length) {
      obj.users = message.users.map((e) => User.toJSON(e));
    }
    if (message.addresses?.length) {
      obj.addresses = message.addresses;
    }
    if (message.matches?.length) {
      obj.matches = message.matches.map((e) => Match.toJSON(e));
    }
    if (message.sets?.length) {
      obj.sets = message.sets.map((e) => Set.toJSON(e));
    }
    if (message.sellOffers?.length) {
      obj.sellOffers = message.sellOffers.map((e) => SellOffer.toJSON(e));
    }
    if (message.pools?.length) {
      obj.pools = message.pools.map((e) => Coin.toJSON(e));
    }
    if (message.cardAuctionPrice !== undefined) {
      obj.cardAuctionPrice = Coin.toJSON(message.cardAuctionPrice);
    }
    if (message.councils?.length) {
      obj.councils = message.councils.map((e) => Council.toJSON(e));
    }
    if (message.runningAverages?.length) {
      obj.runningAverages = message.runningAverages.map((e) => RunningAverage.toJSON(e));
    }
    if (message.images?.length) {
      obj.images = message.images.map((e) => Image.toJSON(e));
    }
    if (message.servers?.length) {
      obj.servers = message.servers.map((e) => Server.toJSON(e));
    }
    if (message.lastCardModified !== undefined) {
      obj.lastCardModified = TimeStamp.toJSON(message.lastCardModified);
    }
    if (message.zealys?.length) {
      obj.zealys = message.zealys.map((e) => Zealy.toJSON(e));
    }
    if (message.encounters?.length) {
      obj.encounters = message.encounters.map((e) => Encounter.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.cardRecords = object.cardRecords?.map((e) => Card.fromPartial(e)) || [];
    message.users = object.users?.map((e) => User.fromPartial(e)) || [];
    message.addresses = object.addresses?.map((e) => e) || [];
    message.matches = object.matches?.map((e) => Match.fromPartial(e)) || [];
    message.sets = object.sets?.map((e) => Set.fromPartial(e)) || [];
    message.sellOffers = object.sellOffers?.map((e) => SellOffer.fromPartial(e)) || [];
    message.pools = object.pools?.map((e) => Coin.fromPartial(e)) || [];
    message.cardAuctionPrice = (object.cardAuctionPrice !== undefined && object.cardAuctionPrice !== null)
      ? Coin.fromPartial(object.cardAuctionPrice)
      : undefined;
    message.councils = object.councils?.map((e) => Council.fromPartial(e)) || [];
    message.runningAverages = object.runningAverages?.map((e) => RunningAverage.fromPartial(e)) || [];
    message.images = object.images?.map((e) => Image.fromPartial(e)) || [];
    message.servers = object.servers?.map((e) => Server.fromPartial(e)) || [];
    message.lastCardModified = (object.lastCardModified !== undefined && object.lastCardModified !== null)
      ? TimeStamp.fromPartial(object.lastCardModified)
      : undefined;
    message.zealys = object.zealys?.map((e) => Zealy.fromPartial(e)) || [];
    message.encounters = object.encounters?.map((e) => Encounter.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
