// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cardchain/cardchain/server.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cardchain.cardchain";

export interface Server {
  reporter: string;
  invalidReports: number;
  validReports: number;
}

function createBaseServer(): Server {
  return { reporter: "", invalidReports: 0, validReports: 0 };
}

export const Server: MessageFns<Server> = {
  encode(message: Server, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reporter !== "") {
      writer.uint32(10).string(message.reporter);
    }
    if (message.invalidReports !== 0) {
      writer.uint32(16).uint64(message.invalidReports);
    }
    if (message.validReports !== 0) {
      writer.uint32(24).uint64(message.validReports);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Server {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reporter = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.invalidReports = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.validReports = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Server {
    return {
      reporter: isSet(object.reporter) ? globalThis.String(object.reporter) : "",
      invalidReports: isSet(object.invalidReports) ? globalThis.Number(object.invalidReports) : 0,
      validReports: isSet(object.validReports) ? globalThis.Number(object.validReports) : 0,
    };
  },

  toJSON(message: Server): unknown {
    const obj: any = {};
    if (message.reporter !== "") {
      obj.reporter = message.reporter;
    }
    if (message.invalidReports !== 0) {
      obj.invalidReports = Math.round(message.invalidReports);
    }
    if (message.validReports !== 0) {
      obj.validReports = Math.round(message.validReports);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Server>, I>>(base?: I): Server {
    return Server.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Server>, I>>(object: I): Server {
    const message = createBaseServer();
    message.reporter = object.reporter ?? "";
    message.invalidReports = object.invalidReports ?? 0;
    message.validReports = object.validReports ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
