// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cardchain/cardchain/user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cardchain.cardchain";

export enum CouncilStatus {
  available = 0,
  unavailable = 1,
  openCouncil = 2,
  startedCouncil = 3,
  UNRECOGNIZED = -1,
}

export function councilStatusFromJSON(object: any): CouncilStatus {
  switch (object) {
    case 0:
    case "available":
      return CouncilStatus.available;
    case 1:
    case "unavailable":
      return CouncilStatus.unavailable;
    case 2:
    case "openCouncil":
      return CouncilStatus.openCouncil;
    case 3:
    case "startedCouncil":
      return CouncilStatus.startedCouncil;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CouncilStatus.UNRECOGNIZED;
  }
}

export function councilStatusToJSON(object: CouncilStatus): string {
  switch (object) {
    case CouncilStatus.available:
      return "available";
    case CouncilStatus.unavailable:
      return "unavailable";
    case CouncilStatus.openCouncil:
      return "openCouncil";
    case CouncilStatus.startedCouncil:
      return "startedCouncil";
    case CouncilStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AirDrop {
  play = 0,
  vote = 1,
  create = 2,
  buy = 3,
  user = 4,
  UNRECOGNIZED = -1,
}

export function airDropFromJSON(object: any): AirDrop {
  switch (object) {
    case 0:
    case "play":
      return AirDrop.play;
    case 1:
    case "vote":
      return AirDrop.vote;
    case 2:
    case "create":
      return AirDrop.create;
    case 3:
    case "buy":
      return AirDrop.buy;
    case 4:
    case "user":
      return AirDrop.user;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AirDrop.UNRECOGNIZED;
  }
}

export function airDropToJSON(object: AirDrop): string {
  switch (object) {
    case AirDrop.play:
      return "play";
    case AirDrop.vote:
      return "vote";
    case AirDrop.create:
      return "create";
    case AirDrop.buy:
      return "buy";
    case AirDrop.user:
      return "user";
    case AirDrop.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface User {
  alias: string;
  ownedCardSchemes: number[];
  ownedPrototypes: number[];
  cards: number[];
  CouncilStatus: CouncilStatus;
  ReportMatches: boolean;
  profileCard: number;
  airDrops: AirDrops | undefined;
  boosterPacks: BoosterPack[];
  website: string;
  biography: string;
  votableCards: number[];
  votedCards: number[];
  earlyAccess: EarlyAccess | undefined;
  OpenEncounters: number[];
  WonEncounters: number[];
}

export interface EarlyAccess {
  active: boolean;
  invitedByUser: string;
  invitedUser: string;
}

export interface BoosterPack {
  setId: number;
  timeStamp: number;
  /** How often the different rarities will appear in a BoosterPack */
  raritiesPerPack: number[];
  /** The chances of the rare beeing a normal rare, an exceptional or a unique */
  dropRatiosPerPack: number[];
}

export interface AirDrops {
  vote: boolean;
  create: boolean;
  buy: boolean;
  play: boolean;
  user: boolean;
}

function createBaseUser(): User {
  return {
    alias: "",
    ownedCardSchemes: [],
    ownedPrototypes: [],
    cards: [],
    CouncilStatus: 0,
    ReportMatches: false,
    profileCard: 0,
    airDrops: undefined,
    boosterPacks: [],
    website: "",
    biography: "",
    votableCards: [],
    votedCards: [],
    earlyAccess: undefined,
    OpenEncounters: [],
    WonEncounters: [],
  };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.alias !== "") {
      writer.uint32(10).string(message.alias);
    }
    writer.uint32(18).fork();
    for (const v of message.ownedCardSchemes) {
      writer.uint64(v);
    }
    writer.join();
    writer.uint32(26).fork();
    for (const v of message.ownedPrototypes) {
      writer.uint64(v);
    }
    writer.join();
    writer.uint32(34).fork();
    for (const v of message.cards) {
      writer.uint64(v);
    }
    writer.join();
    if (message.CouncilStatus !== 0) {
      writer.uint32(48).int32(message.CouncilStatus);
    }
    if (message.ReportMatches !== false) {
      writer.uint32(56).bool(message.ReportMatches);
    }
    if (message.profileCard !== 0) {
      writer.uint32(64).uint64(message.profileCard);
    }
    if (message.airDrops !== undefined) {
      AirDrops.encode(message.airDrops, writer.uint32(74).fork()).join();
    }
    for (const v of message.boosterPacks) {
      BoosterPack.encode(v!, writer.uint32(82).fork()).join();
    }
    if (message.website !== "") {
      writer.uint32(90).string(message.website);
    }
    if (message.biography !== "") {
      writer.uint32(98).string(message.biography);
    }
    writer.uint32(106).fork();
    for (const v of message.votableCards) {
      writer.uint64(v);
    }
    writer.join();
    writer.uint32(114).fork();
    for (const v of message.votedCards) {
      writer.uint64(v);
    }
    writer.join();
    if (message.earlyAccess !== undefined) {
      EarlyAccess.encode(message.earlyAccess, writer.uint32(122).fork()).join();
    }
    writer.uint32(130).fork();
    for (const v of message.OpenEncounters) {
      writer.uint64(v);
    }
    writer.join();
    writer.uint32(138).fork();
    for (const v of message.WonEncounters) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.alias = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.ownedCardSchemes.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ownedCardSchemes.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag === 24) {
            message.ownedPrototypes.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ownedPrototypes.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag === 32) {
            message.cards.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.cards.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.CouncilStatus = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.ReportMatches = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.profileCard = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.airDrops = AirDrops.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.boosterPacks.push(BoosterPack.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.website = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.biography = reader.string();
          continue;
        }
        case 13: {
          if (tag === 104) {
            message.votableCards.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 106) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.votableCards.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 14: {
          if (tag === 112) {
            message.votedCards.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 114) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.votedCards.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.earlyAccess = EarlyAccess.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag === 128) {
            message.OpenEncounters.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 130) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.OpenEncounters.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 17: {
          if (tag === 136) {
            message.WonEncounters.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 138) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.WonEncounters.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      ownedCardSchemes: globalThis.Array.isArray(object?.ownedCardSchemes)
        ? object.ownedCardSchemes.map((e: any) => globalThis.Number(e))
        : [],
      ownedPrototypes: globalThis.Array.isArray(object?.ownedPrototypes)
        ? object.ownedPrototypes.map((e: any) => globalThis.Number(e))
        : [],
      cards: globalThis.Array.isArray(object?.cards) ? object.cards.map((e: any) => globalThis.Number(e)) : [],
      CouncilStatus: isSet(object.CouncilStatus) ? councilStatusFromJSON(object.CouncilStatus) : 0,
      ReportMatches: isSet(object.ReportMatches) ? globalThis.Boolean(object.ReportMatches) : false,
      profileCard: isSet(object.profileCard) ? globalThis.Number(object.profileCard) : 0,
      airDrops: isSet(object.airDrops) ? AirDrops.fromJSON(object.airDrops) : undefined,
      boosterPacks: globalThis.Array.isArray(object?.boosterPacks)
        ? object.boosterPacks.map((e: any) => BoosterPack.fromJSON(e))
        : [],
      website: isSet(object.website) ? globalThis.String(object.website) : "",
      biography: isSet(object.biography) ? globalThis.String(object.biography) : "",
      votableCards: globalThis.Array.isArray(object?.votableCards)
        ? object.votableCards.map((e: any) => globalThis.Number(e))
        : [],
      votedCards: globalThis.Array.isArray(object?.votedCards)
        ? object.votedCards.map((e: any) => globalThis.Number(e))
        : [],
      earlyAccess: isSet(object.earlyAccess) ? EarlyAccess.fromJSON(object.earlyAccess) : undefined,
      OpenEncounters: globalThis.Array.isArray(object?.OpenEncounters)
        ? object.OpenEncounters.map((e: any) => globalThis.Number(e))
        : [],
      WonEncounters: globalThis.Array.isArray(object?.WonEncounters)
        ? object.WonEncounters.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.ownedCardSchemes?.length) {
      obj.ownedCardSchemes = message.ownedCardSchemes.map((e) => Math.round(e));
    }
    if (message.ownedPrototypes?.length) {
      obj.ownedPrototypes = message.ownedPrototypes.map((e) => Math.round(e));
    }
    if (message.cards?.length) {
      obj.cards = message.cards.map((e) => Math.round(e));
    }
    if (message.CouncilStatus !== 0) {
      obj.CouncilStatus = councilStatusToJSON(message.CouncilStatus);
    }
    if (message.ReportMatches !== false) {
      obj.ReportMatches = message.ReportMatches;
    }
    if (message.profileCard !== 0) {
      obj.profileCard = Math.round(message.profileCard);
    }
    if (message.airDrops !== undefined) {
      obj.airDrops = AirDrops.toJSON(message.airDrops);
    }
    if (message.boosterPacks?.length) {
      obj.boosterPacks = message.boosterPacks.map((e) => BoosterPack.toJSON(e));
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    if (message.biography !== "") {
      obj.biography = message.biography;
    }
    if (message.votableCards?.length) {
      obj.votableCards = message.votableCards.map((e) => Math.round(e));
    }
    if (message.votedCards?.length) {
      obj.votedCards = message.votedCards.map((e) => Math.round(e));
    }
    if (message.earlyAccess !== undefined) {
      obj.earlyAccess = EarlyAccess.toJSON(message.earlyAccess);
    }
    if (message.OpenEncounters?.length) {
      obj.OpenEncounters = message.OpenEncounters.map((e) => Math.round(e));
    }
    if (message.WonEncounters?.length) {
      obj.WonEncounters = message.WonEncounters.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.alias = object.alias ?? "";
    message.ownedCardSchemes = object.ownedCardSchemes?.map((e) => e) || [];
    message.ownedPrototypes = object.ownedPrototypes?.map((e) => e) || [];
    message.cards = object.cards?.map((e) => e) || [];
    message.CouncilStatus = object.CouncilStatus ?? 0;
    message.ReportMatches = object.ReportMatches ?? false;
    message.profileCard = object.profileCard ?? 0;
    message.airDrops = (object.airDrops !== undefined && object.airDrops !== null)
      ? AirDrops.fromPartial(object.airDrops)
      : undefined;
    message.boosterPacks = object.boosterPacks?.map((e) => BoosterPack.fromPartial(e)) || [];
    message.website = object.website ?? "";
    message.biography = object.biography ?? "";
    message.votableCards = object.votableCards?.map((e) => e) || [];
    message.votedCards = object.votedCards?.map((e) => e) || [];
    message.earlyAccess = (object.earlyAccess !== undefined && object.earlyAccess !== null)
      ? EarlyAccess.fromPartial(object.earlyAccess)
      : undefined;
    message.OpenEncounters = object.OpenEncounters?.map((e) => e) || [];
    message.WonEncounters = object.WonEncounters?.map((e) => e) || [];
    return message;
  },
};

function createBaseEarlyAccess(): EarlyAccess {
  return { active: false, invitedByUser: "", invitedUser: "" };
}

export const EarlyAccess: MessageFns<EarlyAccess> = {
  encode(message: EarlyAccess, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.active !== false) {
      writer.uint32(8).bool(message.active);
    }
    if (message.invitedByUser !== "") {
      writer.uint32(18).string(message.invitedByUser);
    }
    if (message.invitedUser !== "") {
      writer.uint32(26).string(message.invitedUser);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EarlyAccess {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEarlyAccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.invitedByUser = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.invitedUser = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EarlyAccess {
    return {
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      invitedByUser: isSet(object.invitedByUser) ? globalThis.String(object.invitedByUser) : "",
      invitedUser: isSet(object.invitedUser) ? globalThis.String(object.invitedUser) : "",
    };
  },

  toJSON(message: EarlyAccess): unknown {
    const obj: any = {};
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.invitedByUser !== "") {
      obj.invitedByUser = message.invitedByUser;
    }
    if (message.invitedUser !== "") {
      obj.invitedUser = message.invitedUser;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EarlyAccess>, I>>(base?: I): EarlyAccess {
    return EarlyAccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EarlyAccess>, I>>(object: I): EarlyAccess {
    const message = createBaseEarlyAccess();
    message.active = object.active ?? false;
    message.invitedByUser = object.invitedByUser ?? "";
    message.invitedUser = object.invitedUser ?? "";
    return message;
  },
};

function createBaseBoosterPack(): BoosterPack {
  return { setId: 0, timeStamp: 0, raritiesPerPack: [], dropRatiosPerPack: [] };
}

export const BoosterPack: MessageFns<BoosterPack> = {
  encode(message: BoosterPack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.setId !== 0) {
      writer.uint32(8).uint64(message.setId);
    }
    if (message.timeStamp !== 0) {
      writer.uint32(16).int64(message.timeStamp);
    }
    writer.uint32(26).fork();
    for (const v of message.raritiesPerPack) {
      writer.uint64(v);
    }
    writer.join();
    writer.uint32(34).fork();
    for (const v of message.dropRatiosPerPack) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BoosterPack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBoosterPack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.setId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timeStamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.raritiesPerPack.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.raritiesPerPack.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag === 32) {
            message.dropRatiosPerPack.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.dropRatiosPerPack.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BoosterPack {
    return {
      setId: isSet(object.setId) ? globalThis.Number(object.setId) : 0,
      timeStamp: isSet(object.timeStamp) ? globalThis.Number(object.timeStamp) : 0,
      raritiesPerPack: globalThis.Array.isArray(object?.raritiesPerPack)
        ? object.raritiesPerPack.map((e: any) => globalThis.Number(e))
        : [],
      dropRatiosPerPack: globalThis.Array.isArray(object?.dropRatiosPerPack)
        ? object.dropRatiosPerPack.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: BoosterPack): unknown {
    const obj: any = {};
    if (message.setId !== 0) {
      obj.setId = Math.round(message.setId);
    }
    if (message.timeStamp !== 0) {
      obj.timeStamp = Math.round(message.timeStamp);
    }
    if (message.raritiesPerPack?.length) {
      obj.raritiesPerPack = message.raritiesPerPack.map((e) => Math.round(e));
    }
    if (message.dropRatiosPerPack?.length) {
      obj.dropRatiosPerPack = message.dropRatiosPerPack.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BoosterPack>, I>>(base?: I): BoosterPack {
    return BoosterPack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoosterPack>, I>>(object: I): BoosterPack {
    const message = createBaseBoosterPack();
    message.setId = object.setId ?? 0;
    message.timeStamp = object.timeStamp ?? 0;
    message.raritiesPerPack = object.raritiesPerPack?.map((e) => e) || [];
    message.dropRatiosPerPack = object.dropRatiosPerPack?.map((e) => e) || [];
    return message;
  },
};

function createBaseAirDrops(): AirDrops {
  return { vote: false, create: false, buy: false, play: false, user: false };
}

export const AirDrops: MessageFns<AirDrops> = {
  encode(message: AirDrops, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vote !== false) {
      writer.uint32(8).bool(message.vote);
    }
    if (message.create !== false) {
      writer.uint32(16).bool(message.create);
    }
    if (message.buy !== false) {
      writer.uint32(24).bool(message.buy);
    }
    if (message.play !== false) {
      writer.uint32(32).bool(message.play);
    }
    if (message.user !== false) {
      writer.uint32(40).bool(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AirDrops {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAirDrops();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.vote = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.create = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.buy = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.play = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.user = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AirDrops {
    return {
      vote: isSet(object.vote) ? globalThis.Boolean(object.vote) : false,
      create: isSet(object.create) ? globalThis.Boolean(object.create) : false,
      buy: isSet(object.buy) ? globalThis.Boolean(object.buy) : false,
      play: isSet(object.play) ? globalThis.Boolean(object.play) : false,
      user: isSet(object.user) ? globalThis.Boolean(object.user) : false,
    };
  },

  toJSON(message: AirDrops): unknown {
    const obj: any = {};
    if (message.vote !== false) {
      obj.vote = message.vote;
    }
    if (message.create !== false) {
      obj.create = message.create;
    }
    if (message.buy !== false) {
      obj.buy = message.buy;
    }
    if (message.play !== false) {
      obj.play = message.play;
    }
    if (message.user !== false) {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AirDrops>, I>>(base?: I): AirDrops {
    return AirDrops.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AirDrops>, I>>(object: I): AirDrops {
    const message = createBaseAirDrops();
    message.vote = object.vote ?? false;
    message.create = object.create ?? false;
    message.buy = object.buy ?? false;
    message.play = object.play ?? false;
    message.user = object.user ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
