// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cardchain/cardchain/voting.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cardchain.cardchain";

export enum VoteType {
  fairEnough = 0,
  inappropriate = 1,
  overpowered = 2,
  underpowered = 3,
  UNRECOGNIZED = -1,
}

export function voteTypeFromJSON(object: any): VoteType {
  switch (object) {
    case 0:
    case "fairEnough":
      return VoteType.fairEnough;
    case 1:
    case "inappropriate":
      return VoteType.inappropriate;
    case 2:
    case "overpowered":
      return VoteType.overpowered;
    case 3:
    case "underpowered":
      return VoteType.underpowered;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VoteType.UNRECOGNIZED;
  }
}

export function voteTypeToJSON(object: VoteType): string {
  switch (object) {
    case VoteType.fairEnough:
      return "fairEnough";
    case VoteType.inappropriate:
      return "inappropriate";
    case VoteType.overpowered:
      return "overpowered";
    case VoteType.underpowered:
      return "underpowered";
    case VoteType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface VotingResult {
  cardId: number;
  fairEnoughVotes: number;
  overpoweredVotes: number;
  underpoweredVotes: number;
  inappropriateVotes: number;
  result: string;
}

export interface SingleVote {
  cardId: number;
  voteType: VoteType;
}

function createBaseVotingResult(): VotingResult {
  return {
    cardId: 0,
    fairEnoughVotes: 0,
    overpoweredVotes: 0,
    underpoweredVotes: 0,
    inappropriateVotes: 0,
    result: "",
  };
}

export const VotingResult: MessageFns<VotingResult> = {
  encode(message: VotingResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cardId !== 0) {
      writer.uint32(8).uint64(message.cardId);
    }
    if (message.fairEnoughVotes !== 0) {
      writer.uint32(16).uint64(message.fairEnoughVotes);
    }
    if (message.overpoweredVotes !== 0) {
      writer.uint32(24).uint64(message.overpoweredVotes);
    }
    if (message.underpoweredVotes !== 0) {
      writer.uint32(32).uint64(message.underpoweredVotes);
    }
    if (message.inappropriateVotes !== 0) {
      writer.uint32(40).uint64(message.inappropriateVotes);
    }
    if (message.result !== "") {
      writer.uint32(50).string(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VotingResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVotingResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cardId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.fairEnoughVotes = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.overpoweredVotes = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.underpoweredVotes = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.inappropriateVotes = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.result = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VotingResult {
    return {
      cardId: isSet(object.cardId) ? globalThis.Number(object.cardId) : 0,
      fairEnoughVotes: isSet(object.fairEnoughVotes) ? globalThis.Number(object.fairEnoughVotes) : 0,
      overpoweredVotes: isSet(object.overpoweredVotes) ? globalThis.Number(object.overpoweredVotes) : 0,
      underpoweredVotes: isSet(object.underpoweredVotes) ? globalThis.Number(object.underpoweredVotes) : 0,
      inappropriateVotes: isSet(object.inappropriateVotes) ? globalThis.Number(object.inappropriateVotes) : 0,
      result: isSet(object.result) ? globalThis.String(object.result) : "",
    };
  },

  toJSON(message: VotingResult): unknown {
    const obj: any = {};
    if (message.cardId !== 0) {
      obj.cardId = Math.round(message.cardId);
    }
    if (message.fairEnoughVotes !== 0) {
      obj.fairEnoughVotes = Math.round(message.fairEnoughVotes);
    }
    if (message.overpoweredVotes !== 0) {
      obj.overpoweredVotes = Math.round(message.overpoweredVotes);
    }
    if (message.underpoweredVotes !== 0) {
      obj.underpoweredVotes = Math.round(message.underpoweredVotes);
    }
    if (message.inappropriateVotes !== 0) {
      obj.inappropriateVotes = Math.round(message.inappropriateVotes);
    }
    if (message.result !== "") {
      obj.result = message.result;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VotingResult>, I>>(base?: I): VotingResult {
    return VotingResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VotingResult>, I>>(object: I): VotingResult {
    const message = createBaseVotingResult();
    message.cardId = object.cardId ?? 0;
    message.fairEnoughVotes = object.fairEnoughVotes ?? 0;
    message.overpoweredVotes = object.overpoweredVotes ?? 0;
    message.underpoweredVotes = object.underpoweredVotes ?? 0;
    message.inappropriateVotes = object.inappropriateVotes ?? 0;
    message.result = object.result ?? "";
    return message;
  },
};

function createBaseSingleVote(): SingleVote {
  return { cardId: 0, voteType: 0 };
}

export const SingleVote: MessageFns<SingleVote> = {
  encode(message: SingleVote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cardId !== 0) {
      writer.uint32(8).uint64(message.cardId);
    }
    if (message.voteType !== 0) {
      writer.uint32(16).int32(message.voteType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SingleVote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSingleVote();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cardId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.voteType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SingleVote {
    return {
      cardId: isSet(object.cardId) ? globalThis.Number(object.cardId) : 0,
      voteType: isSet(object.voteType) ? voteTypeFromJSON(object.voteType) : 0,
    };
  },

  toJSON(message: SingleVote): unknown {
    const obj: any = {};
    if (message.cardId !== 0) {
      obj.cardId = Math.round(message.cardId);
    }
    if (message.voteType !== 0) {
      obj.voteType = voteTypeToJSON(message.voteType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SingleVote>, I>>(base?: I): SingleVote {
    return SingleVote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SingleVote>, I>>(object: I): SingleVote {
    const message = createBaseSingleVote();
    message.cardId = object.cardId ?? 0;
    message.voteType = object.voteType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
